import { Character } from "./types";

export const data: Character = {
    id: "0ecc90a8-4473-4c19-bd59-55eee0651d3a",
    characterClass: "android",
    name: "SHALONDA WASKO",
    personalNotes: "",
    pronouns: "HE / HIM",
    thumbnailPath: "images/characters/Mothership Chars 27.jpg",
    strength: 42,
    speed: 21,
    intellect: 47,
    combat: 40,
    sanity: 18,
    fear: 90,
    body: 26,
    stress: 2,
    minStress: 2,
    maxWounds: 3,
    wounds: 0,
    maxHealth: 18,
    health: 18,
    credits: 80,
    trinket: "Coffee Cup, Chipped, reads: HAPPINESS IS MANDATORY",
    patch: "“Cowboy Up” (Crossed Revolvers)",
    traumaResponse:
      "Fear saves made by nearby friendly players are at disadvantage.",
    highScore: 0,
    bonusStat: "speed",
    skillInProgress: null,
    skillTrainingYearsRemaining: 0,
    skillTrainingMonthsRemaining: 0,
    skills: [
      "linguistics",
      "computers",
      "mathematics",
      "archaelogy",
      "rimwise",
      "art",
      "athletics",
      "botany",
      "chemistry",
      "geology",
      "industrialEquipment",
      "juryRigging",
      "militaryTraining",
      "theology",
      "zeroG",
      "zoology",
      "asteroidMining",
      "ecology",
      "explosives",
      "fieldMedicine",
      "firearms",
      "hacking",
      "handToHandCombat",
      "mechanicalRepair",
      "mysticism",
      "pathology",
      "pharmacology",
      "physics",
      "piloting",
      "psychology",
      "wildernessSurvival",
      "ai",
      "command",
      "cybernetics",
      "engineering",
      "exobiology",
      "hyperspace",
      "planetology",
      "robotics",
      "sophontology",
      "surgery",
      "xenoesoterism",
    ],
    equipment: [
      {
        id: "9e9bd59c-9741-43a9-bfa0-3849e25ad12d",
        name: "Bioscanner",
        description:
          "Allows the user to scan the immediate area for signs of life. Generally can scan for 100m in all directions, without being blocked by most known metals. Can tell the location of signs of life, but not what that life is.",
        equipped: true,
        quantity: 1,
        cost: 150,
        baseType: "bioscanner",
      },
      {
        id: "71a79f33-7378-40bd-8ba4-e92feff13f83",
        name: "Assorted Tools",
        description:
          "Wrenches, spanners, screwdrivers, etc. Can be used as weapons (doing the same Damage as a Crowbar).",
        equipped: true,
        quantity: 0,
        cost: 20,
        baseType: "assortedTools",
      },
      {
        id: "2b7e7469-4453-4759-8fed-ea134251288f",
        name: "Automed",
        description:
          "Nanotech pills that assist your body in repairing Damage by granting Advantage to Body Saves meant to repel disease and poison, as well as attempts to heal from rest.",
        equipped: true,
        quantity: 5,
        cost: 1500,
        baseType: "automed",
      },
      {
        id: "397b61e3-bcff-4951-a553-5f0d09218374",
        name: "Binoculars",
        description:
          "20x magnification. Add thermal vision (+300cr) or night vision (+1kcr).",
        equipped: true,
        quantity: 1,
        cost: 300,
        baseType: "binoculars",
      },
      {
        id: "614d7d96-df08-4632-ab53-603409223d81",
        name: "Bioscanner",
        description:
          "Allows the user to scan the immediate area for signs of life. Generally can scan for 100m in all directions, without being blocked by most known metals. Can tell the location of signs of life, but not what that life is.",
        equipped: true,
        quantity: 1,
        cost: 150,
        baseType: "bioscanner",
      },
      {
        id: "a11a54b2-51b4-41b3-800b-1ca20141e18f",
        name: "Body Cam",
        description:
          "A camera worn on your clothing that can stream video back to a control center so your other crewmembers can see what you’re seeing. Add thermal vision (+300cr) or night vision (+1kcr).",
        equipped: true,
        quantity: 1,
        cost: 50,
        baseType: "bodyCam",
      },
      {
        id: "e2c58873-c4bd-450a-9720-4e9764282b36",
        name: "Chemlight",
        description:
          "Small disposable glowsticks capable of dim illumination in a 1m radius.",
        equipped: true,
        quantity: 5,
        cost: 5,
        baseType: "chemlight",
      },
      {
        id: "d91e2c74-cbd5-481e-9094-6512d8b34d8d",
        name: "Long-range Comms",
        description:
          "Rucksack-sized communication device for use in surface-to-ship comunication.",
        equipped: true,
        quantity: 1,
        cost: 65,
        baseType: "longrangeComms",
      },
      {
        id: "b2241949-dbc5-4e95-b9a9-654efa74c46d",
        name: "Short-range comms",
        description:
          "Allows communication from ship-to-ship within a reasonable distance, as well as surface-to-surface within a dozen kilometers. Blocked by radio jammer.",
        equipped: true,
        quantity: 1,
        cost: 30,
        baseType: "shortrangecomms",
      },
      {
        id: "9f87a41f-26b9-4c43-ad0c-854d76fc0243",
        name: "Cybernetic Diagnostic Scanner",
        description:
          "Allows the user to scan androids and other cybernetic organisms in order to diagnose any physical or mental issues they may be having. Often distrusted by androids.",
        equipped: true,
        quantity: 1,
        cost: 500,
        baseType: "cyberneticDiagnostic",
      },
      {
        id: "79ddeda6-b02f-4264-9507-8687af65ee64",
        name: "Drone (Recon)",
        description:
          "Remote controlled drone. Requires two hands to operate receiver. Can fly up to 450m high, to a distance of 3km from operator. Battery operated. Can run for 2 hours. Can record and transmit footage to receiver. If purchased separately, can be equipped with up to two of the following (at their regular cost): binoculars, radio jammer, Geiger counter, medscanner, personal locator, infrared goggles, emergency beacon, cybernetic diagnostic scanner, bioscanner.",
        equipped: true,
        quantity: 1,
        cost: 5000,
        baseType: "droneRecon",
      },
      {
        id: "2a0fa003-306e-4482-956b-fe42dde145bd",
        name: "Drone (Salvage)",
        description:
          "Remote controlled drone. Requires two hands to operate receiver. Can fly up to 10m high, to anywhere Long Range from the operator. Battery operated. Can run for 2 hours. Can record and transmit footage to receiver. Can be equipped with a laser cutter if purchased separately. Can carry up to 225kg.",
        equipped: true,
        quantity: 1,
        cost: 10000,
        baseType: "droneSalvage",
      },
      {
        id: "ce6f905e-b132-4cf2-bb59-317169dd4ff5",
        name: "Electronic Tool Set",
        description:
          "A full set of tools for doing detailed repair or construction work on electronics.",
        equipped: true,
        quantity: 1,
        cost: 650,
        baseType: "electronicToolSet",
      },
      {
        id: "8bb41c35-3cbc-43d9-a43c-2adeab9c6afa",
        name: "Emergency Beacon",
        description:
          "A small device that sends up a flare and then emits a loud beep every few seconds. Additionally, sends out a call on all radio channels to ships or vehicles in the area, but can be blocked by a radio jammer.",
        equipped: true,
        quantity: 1,
        cost: 30,
        baseType: "emergencyBeacon",
      },
      {
        id: "9ced184e-2273-4a2e-92ca-55e9f8397b07",
        name: "Exoloader",
        description:
          "Open-air mechanical exo-skeleton used for heavy lifting (up to 5000kg). Loader claws deal 1 Wound. User can only wear Standard Crew Attire or Standard Battle Dress while operating. Battery operated (48 hours of use).",
        equipped: true,
        quantity: 1,
        cost: 100000,
        baseType: "exoloader",
      },
      {
        id: "ea8a8b6b-d312-44ec-a022-6ce813f1222d",
        name: "Explosives & Detonator",
        description:
          "Explosive charge powerful enough to blow open an airlock. All Close organisms must make a Body Save or take a Wound (Explosive). Detonator works at Long Range, but can be blocked by a radio jammer.",
        equipped: true,
        quantity: 1,
        cost: 500,
        baseType: "explosivesDetonator",
      },
      {
        id: "a1f3ad43-5634-490b-ac20-31f24563ab69",
        name: "First Aid Kit",
        description:
          "An assortment of bandages and treatments to help stop bleeding, bandage cuts, and treat other minor injuries.",
        equipped: true,
        quantity: 1,
        cost: 75,
        baseType: "firstAidKit",
      },
      {
        id: "e7531adb-f7af-4f5b-9a57-9ae5c55f5148",
        name: "Flashlight",
        description:
          "Handheld or shoulder mounted. Illuminates 10m ahead of the user.",
        equipped: true,
        quantity: 1,
        cost: 10,
        baseType: "flashlight",
      },
      {
        id: "1d7e67e8-6a71-46da-a16b-dc28a90ce08d",
        name: "Foldable Stretcher",
        description:
          "Portable stretcher that can fit within a rucksack. Allows the user to safely strap down the patient and carry them to a location where their wounds can be better treated. Unfolds to roughly 2m.",
        equipped: true,
        quantity: 1,
        cost: 100,
        baseType: "foldableStretcher",
      },
      {
        id: "7afa3897-f77a-4d9e-91ed-865c7a15dbde",
        name: "Geiger Counter",
        description: "Detects radiation and displays radiation levels.",
        equipped: true,
        quantity: 1,
        cost: 20,
        baseType: "geigerCounter",
      },
      {
        id: "c5884110-e11e-42df-9858-584a464d1bbe",
        name: "Heads-Up Display (HUD)",
        description:
          "Often worn by marines, the HUD allows the wearer to see through the body cams of others in their unit, and can connect to any smart-link upgaded weapon.",
        equipped: true,
        quantity: 1,
        cost: 75,
        baseType: "headsUpDisplayHUD",
      },
      {
        id: "e7dbea4f-110d-4d6e-b195-0741fe1363a8",
        name: "Infrared Goggles",
        description:
          "Allows the wearer to see heat signatures, sometimes up to several hours old. Add night vision for (+1kcr).",
        equipped: true,
        quantity: 1,
        cost: 100,
        baseType: "infraredGoggles",
      },
      {
        id: "ab4f9c16-4a0c-473b-9d3d-413ad2fa078f",
        name: "Jetpack",
        description:
          "Allows wearer to fly up to 100m high. Fuel-operated for 1 hour. Deals 1d100 DMG if destroyed.",
        equipped: true,
        quantity: 1,
        cost: 75000,
        baseType: "jetpack",
      },
      {
        id: "533e9bae-cadc-4ac8-8e67-a85fac0564fe",
        name: "Lockpick Set",
        description:
          "A highly advanced set of tools meant for hacking basic airlock and electronic door systems.",
        equipped: true,
        quantity: 1,
        cost: 40,
        baseType: "lockpickSet",
      },
      {
        id: "636712d1-2b0b-4436-bb19-c6b139d839ae",
        name: "MRE",
        description:
          "“Meals, Ready-to-Eat.” Self-contained, individual field rations in lightweight packaging. Each one has sufficient sustenance for a single person for one day (does not include water).",
        equipped: true,
        quantity: 7,
        cost: 70,
        baseType: "mre",
      },
      {
        id: "44244b64-2345-433f-a6bc-719d4f92cb34",
        name: "Mag-boots",
        description:
          "Grants a magnetic grip to the wearer, allowing them to easily walk on the exterior of a ship (in space, while docked, or free-floating), metal based asteroids, or any other magnetic surface.",
        equipped: true,
        quantity: 1,
        cost: 55,
        baseType: "magboots",
      },
      {
        id: "6e15c923-2790-4a1f-b492-2e02ca3261f6",
        name: "Medscanner",
        description:
          "Allows the user to scan a living or dead body to analyze it for disease or abnormalities, without having to do a biopsy (or autopsy). Results are often non-instantaneous and may require a lab for analysis.",
        equipped: true,
        quantity: 1,
        cost: 150,
        baseType: "medscanner",
      },
      {
        id: "0015660a-0c8a-48a6-9773-c06a1dead4fc",
        name: "MoHab Unit",
        description: "Tent, canteen, stove, rucksack, compass, and sleeping bag.",
        equipped: true,
        quantity: 1,
        cost: 1000,
        baseType: "moHabUnit",
      },
      {
        id: "8963d89f-6d8e-4f6e-bcb4-342495b0cf1c",
        name: "Mylar Blanket",
        description:
          "Lightweight blanket made of heat-reflective material. Often used for thermal control of patients suffering from extreme cold or other trauma.",
        equipped: true,
        quantity: 1,
        cost: 10,
        baseType: "mylarBlanket",
      },
      {
        id: "ad441a9b-c710-4b7f-9162-3d3a11f75ae2",
        name: "Oxygen Tank",
        description:
          "When attached to a vaccsuit provides up to 12 hours of oxygen under normal circumstances, 4 hours under stressful circumstances. Explosive.",
        equipped: true,
        quantity: 1,
        cost: 50,
        baseType: "oxygenTank",
      },
      {
        id: "6b49568c-74b7-42a3-928f-8fded50a81ea",
        name: "Paracord (50m)",
        description: "General purpose lightweight nylon rope.",
        equipped: true,
        quantity: 1,
        cost: 10,
        baseType: "paracord",
      },
      {
        id: "f65f41ff-f8eb-4a17-9483-6277736d262b",
        name: "Patch Kit",
        description:
          "Repairs punctured and torn vaccsuits, restoring their space readiness. Patched vaccsuits have an AP of 1.",
        equipped: true,
        quantity: 3,
        cost: 200,
        baseType: "patchKit",
      },
      {
        id: "578f68bc-60f5-423b-baac-bc7ef2b63de7",
        name: "Personal Locator",
        description:
          "Allows crewmembers at a control center (or on the bridge of a ship) to track the location of the wearer.",
        equipped: true,
        quantity: 1,
        cost: 45,
        baseType: "personalLocator",
      },
      {
        id: "8d6ff2d3-6b5a-439d-8c31-503eba44a65d",
        name: "Pet (Organic)",
        description:
          "Small to medium-sized organic pet animal. Larger or rare pets cost 2d10x.",
        equipped: true,
        quantity: 1,
        cost: 200000,
        baseType: "petOrganic",
      },
      {
        id: "116e0071-8c33-4cb8-97a3-7b11dc59a388",
        name: "Pet (Synthetic)",
        description:
          "Small to medium-sized synthetic pet animal. Larger or rare pets cost 2d10x.",
        equipped: true,
        quantity: 1,
        cost: 15000,
        baseType: "petSynthetic",
      },
      {
        id: "e506c16b-151b-4991-9d61-240688a9624b",
        name: "Pain Pills",
        description:
          "When ingested, immediately restores 1d10 health and lowers Stress by 1. There is a danger of addiction and/or overdose if used frequently.",
        equipped: true,
        quantity: 5,
        cost: 450,
        baseType: "painPills",
      },
      {
        id: "35334853-396f-4c40-b14d-2ad82ae224da",
        name: "Radiation Pills",
        description:
          "Reduces Radiation Damage (see pg. xx.x) by 2d10 for 2d10 minutes.",
        equipped: true,
        quantity: 5,
        cost: 200,
        baseType: "radiationPills",
      },
      {
        id: "a9e6ce79-f85d-4cf8-8a0a-d6da2515a113",
        name: "Portable Computer Terminal",
        description:
          "Flat computer monitor, keyboard and interface which allows the user to hack into pre-existing computers and networks, as well as perform standard computer tasks.",
        equipped: true,
        quantity: 1,
        cost: 1500,
        baseType: "portableComputerTerminal",
      },
      {
        id: "a4470254-db14-46b1-9d3d-f7cbb8aa0fbc",
        name: "Radio Jammer",
        description:
          "Rucksack-sized device which, when activated, renders incomprehensible the radio signals of all within 100km.",
        equipped: true,
        quantity: 1,
        cost: 175,
        baseType: "radioJammer",
      },
      {
        id: "6838bc5c-f01b-4fca-b224-19d9fbb4a3fe",
        name: "Rebreather",
        description:
          "When worn, filters toxic air and/or allows for underwater breathing for up to twenty minutes at a time without resurfacing. Can be connected to an oxygen tank.",
        equipped: true,
        quantity: 1,
        cost: 45,
        baseType: "rebreather",
      },
      {
        id: "26684d34-dedb-427c-9e49-6bdcd9a6f72e",
        name: "Rucksack",
        description: "Large, durable, waterproof backpack.",
        equipped: true,
        quantity: 1,
        cost: 50,
        baseType: "rucksack",
      },
      {
        id: "16199f8d-2c60-4378-ba4f-7167b8598f93",
        name: "Sample Collection Kit",
        description:
          "Used to research xenoflora and xenofauna in the field. Can take vital signs, DNA samples ,and collect other data on foreign material. Results may not be instaneous and may require a lab for complete analysis.",
        equipped: true,
        quantity: 1,
        cost: 250,
        baseType: "sampleKit",
      },
      {
        id: "ead3051e-cd0f-407f-8e8b-4d7bad11d7ad",
        name: "Smart-link Add-On",
        description:
          "Grants remote viewing, recording, and operation of a ranged weapon as well as +5 DMG.",
        equipped: true,
        quantity: 1,
        cost: 10000,
        baseType: "smartLinkAddOn",
      },
      {
        id: "a74517cd-3f6c-493e-b981-5558ba8075be",
        name: "Stimpak",
        description:
          "Cures cryosickness. Restores 1d10 Health and grants Advantage to Strength and Combat for 2d10 minutes. There is a danger of addiction and/or overdose if used frequently. ",
        equipped: true,
        quantity: 5,
        cost: 600,
        baseType: "stimpak",
      },
      {
        id: "09c4e92e-4812-43f2-8354-78bfcfee8791",
        name: "Water Filtration Device",
        description:
          "Can pump 50 liters of filtered water per hour from even the most brackish swamps.",
        equipped: true,
        quantity: 1,
        cost: 15,
        baseType: "waterFiltrationDevice",
      },
    ],
    armor: [
      {
        armorType: "standardCrewAttire",
        id: "1f247c9b-2883-4c49-abce-46770e19dceb",
        name: "Standard Crew Attire",
        equipped: true,
        armorPoints: 1,
        cost: 20,
        oxygenSupply: 0,
        notes: "",
        armorSpeed: "normal",
      },
      {
        armorType: "advancedBattleDress",
        id: "55d58171-d63d-4aa7-8afd-05b50c48c209",
        name: "Advanced Battle Dress",
        equipped: true,
        armorPoints: 10,
        cost: 1500,
        oxygenSupply: 1,
        notes:
          "Includes short-range comms, body cam, headlamp, HUD, exoskeleton weave ([+] on Strength Checks), and radiation shielding. Ignores the first Wound you suffer.",
        armorSpeed: "disadvantage",
      },
      {
        armorType: "standardBattleDress",
        id: "2008b970-e981-4d46-8bda-9e46aeeccaa9",
        name: "Standard Battle Dress",
        equipped: true,
        armorPoints: 7,
        cost: 750,
        oxygenSupply: 0,
        notes: "Includes short-range comms.",
        armorSpeed: "normal",
      },
      {
        armorType: "standardCrewAttire",
        id: "b9508895-755f-4cb2-bced-bc5864b18d35",
        name: "Standard Crew Attire",
        equipped: true,
        armorPoints: 1,
        cost: 20,
        oxygenSupply: 0,
        notes: "",
        armorSpeed: "normal",
      },
      {
        armorType: "hazardSuit",
        id: "76be828f-38e9-4b68-9ed2-8cec406225c9",
        name: "Hazard Suit",
        equipped: true,
        armorPoints: 5,
        cost: 750,
        oxygenSupply: 1,
        notes:
          "Includes air filter, extreme heat/cold protection, hydration reclamation (1L of water lasts 4 days), short-range comms, headlamp, and radiation shielding.",
        armorSpeed: "normal",
      },
      {
        armorType: "vaccsuit",
        id: "4999a652-c93a-42c3-a6ce-c19acd965a25",
        name: "Vaccsuit",
        equipped: true,
        armorPoints: 3,
        cost: 1000,
        oxygenSupply: 12,
        notes:
          "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
        armorSpeed: "disadvantage",
      },
    ],
    weapons: [
      {
        id: "049414da-9cd0-4ac0-a7f0-49e65031b5c1",
        name: "",
        equipped: true,
        cost: 50,
        weaponRange: "adjacent",
        damageString: "1d5 DMG",
        shots: null,
        magazineSize: null,
        critical: "Bleeding [+]",
        special: "",
        weaponType: "Scalpel",
        magazines: null,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "scalpel",
      },
      {
        id: "3574dc47-35c8-4e22-8752-73a1374bedd3",
        name: "ARMA 29",
        equipped: true,
        cost: 1200,
        weaponRange: "long",
        damageString: "2d10 DMG",
        shots: 4,
        magazineSize: 4,
        critical: "Gunshot",
        special: "Can be held one-handed.",
        weaponType: "SMG",
        magazines: 1,
        damage: [{ damageType: "xd10", amount: 2, rollMode: null }],
        baseType: "smg",
      },
      {
        id: "cbe6bc4c-ea53-4ed7-a28b-334ddd4347e1",
        name: "D&C 7",
        equipped: true,
        cost: 850,
        weaponRange: "close",
        damageString: "1 DMG",
        shots: 6,
        magazineSize: 6,
        critical: "Blunt Force",
        special:
          "If DMG dealt: target must Body Save or be unconscious 1d10 rounds.",
        weaponType: "Tranq Pistol",
        magazines: 1,
        damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
        baseType: "tranqPistol",
      },
      {
        id: "b6f44416-34bf-4ba9-abf3-e5f66c1d7872",
        name: "F20 “Arbiter”",
        equipped: true,
        cost: 2000,
        weaponRange: "long",
        damageString: "3d10 DMG",
        shots: 5,
        magazineSize: 5,
        critical: "Gunshot",
        special: "Pump-action grenade launcher holds x3 frag grenades.",
        weaponType: "Pulse Rifle",
        magazines: 1,
        damage: [{ damageType: "xd10", amount: 3, rollMode: null }],
        baseType: "pulseRifle",
      },
      {
        id: "61aa11ff-7c02-473c-8ec1-89bd57e322e5",
        name: "FN Slug",
        equipped: true,
        cost: 750,
        weaponRange: "close",
        damageString: "1d10 DMG [+]",
        shots: 6,
        magazineSize: 6,
        critical: "Gunshot",
        special: "",
        weaponType: "Revolver",
        magazines: 1,
        damage: [{ damageType: "xd10", amount: 1, rollMode: "advantage" }],
        baseType: "revolver",
      },
      {
        id: "a2e7c6f0-42e0-48c4-833f-e04aad946fde",
        name: "",
        equipped: true,
        cost: 70,
        weaponRange: "long",
        damageString: "1d5-1 Wounds",
        shots: 1,
        magazineSize: 1,
        critical: "Fire/Explosives",
        special: "All Close must Body Save to avoid.",
        weaponType: "Frag Grenade",
        magazines: 1,
        damage: [{ damageType: "d5MinusOneWounds", amount: 1, rollMode: null }],
        baseType: "fragGrenade",
      },
      {
        id: "af8bfb9a-4207-4eaa-a2dc-df67c0054b7c",
        name: "KANO X9",
        equipped: true,
        cost: 1400,
        weaponRange: "close",
        damageString: "1 Wound",
        shots: 4,
        magazineSize: 4,
        critical: "Gunshot",
        special: "1d10 DMG at Long Range.",
        weaponType: "Combat Shotgun",
        magazines: 1,
        damage: [
          { damageType: "fixedWounds", amount: 1, rollMode: null },
          { damageType: "xd10", amount: 1, rollMode: null },
        ],
        baseType: "combatShotgun",
      },
      {
        id: "3ffb8ddc-4d79-4953-a905-5d07f85acae2",
        name: "Overmatch Arms SW-512",
        equipped: true,
        cost: 1800,
        weaponRange: "long",
        damageString: "4d10[+] DMG",
        shots: 5,
        magazineSize: 5,
        critical: "Gunshot[+]",
        special:
          "Two-handed. Heavy. Barrel can be maneuvered to fire around corners.",
        weaponType: "Heavy Machine Gun",
        magazines: 1,
        damage: [{ damageType: "xd10", amount: 4, rollMode: "advantage" }],
        baseType: "heavyMachineGun",
      },
      {
        id: "40b5d1c5-6155-4087-9b2c-d383045cde8c",
        name: "Peabody",
        equipped: true,
        cost: 85,
        weaponRange: "long",
        damageString: "1d5 DMG",
        shots: 2,
        magazineSize: 2,
        critical: "Fire/Explosives [-]",
        special: "High intensity flare visible day and night from Long Range.",
        weaponType: "Flare Gun",
        magazines: 1,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "flareGun",
      },
      {
        id: "1a79f24a-47cb-4139-983b-10ab1d8a5b10",
        name: "SK 109 Seeker",
        equipped: true,
        cost: 12000,
        weaponRange: "long",
        damageString: "1d10x10 DMG",
        shots: 3,
        magazineSize: 3,
        critical: "Gunshot[+]",
        special: "If not braced/prone when firing, Body Save or be knocked down.",
        weaponType: "Smart Rifle",
        magazines: 1,
        damage: [{ damageType: "d10x10", amount: 1, rollMode: null }],
        baseType: "smartRifle",
      },
      {
        id: "6a29732a-0fbd-4d2f-966e-ffee40518799",
        name: "EVA MK II",
        equipped: true,
        cost: 250,
        weaponRange: "adjacent",
        damageString: "1d10 DMG",
        shots: null,
        magazineSize: null,
        critical: "Bleeding",
        special: "Can cut through airlock doors.",
        weaponType: "Hand Welder",
        magazines: null,
        damage: [{ damageType: "xd10", amount: 1, rollMode: null }],
        baseType: "handWelder",
      },
      {
        id: "c85e0ee5-22b8-4c86-a583-5de6bf339242",
        name: "HAN-290",
        equipped: true,
        cost: 350,
        weaponRange: "close",
        damageString: "1d10 DMG + 2d10 DMG when removed.",
        shots: 1,
        magazineSize: 1,
        critical: "Bleeding [+]",
        special: "100m micro-filament. Body Save or become entangled.",
        weaponType: "Rigging Gun",
        magazines: 1,
        damage: [
          { damageType: "xd10", amount: 1, rollMode: null },
          { damageType: "xd10", amount: 2, rollMode: null },
        ],
        baseType: "riggingGun",
      },
      {
        id: "b303958f-bd9c-4f8d-8886-f020619ecf86",
        name: "Halls B Series",
        equipped: true,
        cost: 275,
        weaponRange: "close",
        damageString: "1 DMG",
        shots: 3,
        magazineSize: 3,
        critical: "Blunt Force",
        special:
          "Body Save or become stuck. Strength [-] Check to escape. Quick-hardening foam covers 1sqm.",
        weaponType: "Foam Gun",
        magazines: 1,
        damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
        baseType: "foamGun",
      },
      {
        id: "9c3ae3e8-f570-4dff-b873-3ce7258332be",
        name: "MNC Mode",
        equipped: true,
        cost: 1200,
        weaponRange: "long",
        damageString: "1d100 DMG",
        shots: 6,
        magazineSize: 6,
        critical: "Bleeding [+] or Gore [+]",
        special:
          "Two-handed. Heavy. Must recharge between shots. Reload: 1hr (power), 6hr (solar).",
        weaponType: "Laser Cutter",
        magazines: 1,
        damage: [{ damageType: "d100", amount: 1, rollMode: null }],
        baseType: "laserCutter",
      },
      {
        id: "ab7d880c-5a00-490e-a528-23d77278c5db",
        name: "Ramhorn",
        equipped: true,
        cost: 2000,
        weaponRange: "close",
        damageString: "1 Wound",
        shots: 4,
        magazineSize: 4,
        critical: "Fire/Explosives [+]",
        special: "If liquid fuel tank is destroyed, 1 Wound to all Close.",
        weaponType: "Flamethrower",
        magazines: 1,
        damage: [{ damageType: "fixedWounds", amount: 1, rollMode: null }],
        baseType: "flamethrower",
      },
      {
        id: "f6b3afcc-9838-4ff7-aabf-4111cf478a1c",
        name: "Rosco SS6",
        equipped: true,
        cost: 150,
        weaponRange: "close",
        damageString: "1d5 DMG",
        shots: 32,
        magazineSize: 32,
        critical: "Bleeding",
        special: "",
        weaponType: "Nailgun",
        magazines: 1,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "nailGun",
      },
      {
        id: "6c9d6e1b-aac1-4cef-99a5-aa414a3b9bd5",
        name: "",
        equipped: true,
        cost: 150,
        weaponRange: "adjacent",
        damageString: "2d10 DMG [+]",
        shots: null,
        magazineSize: null,
        critical: "Gore [+]",
        special: "",
        weaponType: "Boarding Axe",
        magazines: null,
        damage: [{ damageType: "xd10", amount: 2, rollMode: "advantage" }],
        baseType: "boardingAxe",
      },
      {
        id: "f66cc43a-d7bc-4ba3-8dbc-3ab8be4815c3",
        name: "",
        equipped: true,
        cost: 50,
        weaponRange: "adjacent",
        damageString: "1d5 DMG",
        shots: null,
        magazineSize: null,
        critical: "Blunt Force [+]",
        special: "",
        weaponType: "Crowbar",
        magazines: null,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "crowbar",
      },
      {
        id: "083aca86-7c27-4859-94be-8a865558797b",
        name: "",
        equipped: true,
        cost: 50,
        weaponRange: "adjacent",
        damageString: "1d5 DMG",
        shots: null,
        magazineSize: null,
        critical: "Bleeding [+]",
        special: "",
        weaponType: "Scalpel",
        magazines: null,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "scalpel",
      },
      {
        id: "4294c83d-8796-4f3c-acda-0e8a97a750af",
        name: "",
        equipped: true,
        cost: 115,
        weaponRange: "adjacent",
        damageString: "1d5 DMG",
        shots: null,
        magazineSize: null,
        critical: "Blunt Force",
        special: "Body Save or stunned 1 round.",
        weaponType: "Stun Baton",
        magazines: null,
        damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
        baseType: "stunBaton",
      },
      {
        id: "0f56f168-fae2-4834-8d4d-50728ccab5c5",
        name: "",
        equipped: true,
        cost: 500,
        weaponRange: "adjacent",
        damageString: "3d10 DMG",
        shots: null,
        magazineSize: null,
        critical: "Bleeding + Gore",
        special:
          "When dealing a Wound, roll on BOTH the Bleeding AND Gore columns.",
        weaponType: "Vibechete",
        magazines: null,
        damage: [{ damageType: "xd10", amount: 3, rollMode: null }],
        baseType: "vibechete",
      },
    ],
    items: [],
    conditions: [
      { conditionType: "phobia" },
      { conditionType: "haunted" },
      { conditionType: "laserFocus" },
      { conditionType: "overwhelmed" },
      { conditionType: "coward" },
      { conditionType: "nightmares" },
      { conditionType: "lossOfConfidence" },
      { conditionType: "deflated" },
      { conditionType: "doomed" },
      { conditionType: "paranoid" },
      { conditionType: "deathWish" },
      { conditionType: "catatonic" },
      { conditionType: "spiraling" },
      { conditionType: "heartAttack" },
    ],
    creationComplete: true,
    woundEffects: [],
    contractors: [
      {
        type: "archaeologist",
        id: "bc58ba77-f7ad-4391-aa50-51da3582e637",
        occupation: "Archaeologist",
        name: "Vergie Mccandless",
        pronouns: "She / Her",
        thumbnailPath: "images/characters/Mothership Chars 19.jpg",
        salary: 1000,
        combat: 20,
        instinct: 15,
        wounds: 0,
        maxWounds: 1,
        loyalty: 16,
        motivation: "",
        equipment: [
          {
            id: "bfe89e47-9519-497a-820d-2bca1f0d9a88",
            name: "Pain Pills",
            description:
              "When ingested, immediately restores 1d10 health and lowers Stress by 1. There is a danger of addiction and/or overdose if used frequently.",
            equipped: true,
            quantity: 5,
            cost: 450,
            baseType: "painPills",
          },
          {
            id: "34242b6c-6a70-48e8-be0d-28ddd1c7ab6d",
            name: "Electronic Tool Set",
            description:
              "A full set of tools for doing detailed repair or construction work on electronics.",
            equipped: true,
            quantity: 1,
            cost: 650,
            baseType: "electronicToolSet",
          },
        ],
        armor: [
          {
            armorType: "hazardSuit",
            id: "b12ccfd6-2ede-4378-a1f2-eccd13d15dcb",
            name: "Hazard Suit",
            equipped: true,
            armorPoints: 5,
            cost: 750,
            oxygenSupply: 1,
            notes:
              "Includes air filter, extreme heat/cold protection, hydration reclamation (1L of water lasts 4 days), short-range comms, headlamp, and radiation shielding.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "dac6fa11-9e10-41e7-becc-8e79a1bb59ec",
            name: "Ramhorn",
            equipped: true,
            cost: 2000,
            weaponRange: "close",
            damageString: "1 Wound",
            shots: 4,
            magazineSize: 4,
            critical: "Fire/Explosives [+]",
            special: "If liquid fuel tank is destroyed, 1 Wound to all Close.",
            weaponType: "Flamethrower",
            magazines: 0,
            damage: [{ damageType: "fixedWounds", amount: 1, rollMode: null }],
            baseType: "flamethrower",
          },
        ],
        items: [],
      },
      {
        type: "asteroidMiner",
        id: "d7d691ff-f009-4e94-8a0b-4ea66a51db73",
        occupation: "Asteroid Miner",
        name: "Greene Jelinek",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 12.jpg",
        salary: 2000,
        combat: 25,
        instinct: 25,
        wounds: 0,
        maxWounds: 2,
        loyalty: 30,
        motivation: "",
        equipment: [],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "e0fbd361-dd77-4df9-84cb-8f56c9f5a0ee",
            name: "Standard Crew Attire",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "2aecfbf2-4dc9-4d0a-9b23-8cee43f6e9cb",
            name: "Rosco SS6",
            equipped: true,
            cost: 150,
            weaponRange: "close",
            damageString: "1d5 DMG",
            shots: 32,
            magazineSize: 32,
            critical: "Bleeding",
            special: "",
            weaponType: "Nailgun",
            magazines: 0,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "nailGun",
          },
        ],
        items: [
          {
            title: "Head Lamp",
            id: "3c06fbf3-11d7-4c8d-9129-f6791eadfdfd",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
          {
            title: "Satchel",
            id: "56bb8194-79ae-4088-bfdc-cb2b1a86348d",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
          {
            title: "Lunch Box",
            id: "cf041b93-54a4-4d17-9d26-401e2cb2286f",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
        ],
      },
      {
        type: "android",
        id: "ba72decc-e939-4829-9619-e94ba637eb9f",
        occupation: "Android",
        name: "Tim Quisenberry",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 22.jpg",
        salary: 2500,
        combat: 20,
        instinct: 35,
        wounds: 0,
        maxWounds: 2,
        loyalty: 17,
        motivation: "",
        equipment: [
          {
            id: "c9b94407-f45f-4e19-8580-df052c5606f3",
            name: "Paracord (50m)",
            description: "General purpose lightweight nylon rope.",
            equipped: true,
            quantity: 1,
            cost: 10,
            baseType: "paracord",
          },
        ],
        armor: [
          {
            armorType: "standardBattleDress",
            id: "7e7b3eef-aa35-4513-9004-4d1c323fe1b3",
            name: "Standard Battle Dress",
            equipped: true,
            armorPoints: 7,
            cost: 750,
            oxygenSupply: 0,
            notes: "Includes short-range comms.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "27b159fd-ba8c-4b8b-be4a-2629810762fc",
            name: "D&C 7",
            equipped: true,
            cost: 850,
            weaponRange: "close",
            damageString: "1 DMG",
            shots: 3,
            magazineSize: 6,
            critical: "Blunt Force",
            special:
              "If DMG dealt: target must Body Save or be unconscious 1d10 rounds.",
            weaponType: "Tranq Pistol",
            magazines: 0,
            damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
            baseType: "tranqPistol",
          },
        ],
        items: [],
      },
      {
        type: "bodyguard",
        id: "2bdc7f82-9440-40f1-8cba-cab633f07573",
        occupation: "Bodyguard",
        name: "Graydon Trail",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 55.jpg",
        salary: 2000,
        combat: 30,
        instinct: 25,
        wounds: 0,
        maxWounds: 2,
        loyalty: 23,
        motivation: "",
        equipment: [
          {
            id: "31201999-0bff-4307-8f09-d358090d817d",
            name: "Stimpak",
            description:
              "Cures cryosickness. Restores 1d10 Health and grants Advantage to Strength and Combat for 2d10 minutes. There is a danger of addiction and/or overdose if used frequently. ",
            equipped: true,
            quantity: 1,
            cost: 600,
            baseType: "stimpak",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "69111c53-9bdc-4912-ba4b-956d12422f6d",
            name: "Tank Top and Camo Pants",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "b449a402-bad9-4376-aac3-d1584be06501",
            name: "Combat Knife",
            equipped: true,
            cost: 50,
            weaponRange: "adjacent",
            damageString: "1d5 DMG",
            shots: null,
            magazineSize: null,
            critical: "Bleeding [+]",
            special: "",
            weaponType: "Scalpel",
            magazines: null,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "scalpel",
          },
        ],
        items: [],
      },
      {
        type: "captain",
        id: "674bac88-e59c-42a0-8d4c-4a233bd30410",
        occupation: "Captain",
        name: "Thor Moir",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 11.jpg",
        salary: 8000,
        combat: 30,
        instinct: 40,
        wounds: 0,
        maxWounds: 3,
        loyalty: 15,
        motivation: "",
        equipment: [
          {
            id: "2986a88d-e2df-4ff5-a6a9-13ba2ecc5b66",
            name: "Paracord (50m)",
            description: "General purpose lightweight nylon rope.",
            equipped: true,
            quantity: 1,
            cost: 10,
            baseType: "paracord",
          },
          {
            id: "9e7881f8-5ecd-4877-a11f-73131e42fc0d",
            name: "Drone (Recon)",
            description:
              "Remote controlled drone. Requires two hands to operate receiver. Can fly up to 450m high, to a distance of 3km from operator. Battery operated. Can run for 2 hours. Can record and transmit footage to receiver. If purchased separately, can be equipped with up to two of the following (at their regular cost): binoculars, radio jammer, Geiger counter, medscanner, personal locator, infrared goggles, emergency beacon, cybernetic diagnostic scanner, bioscanner.",
            equipped: true,
            quantity: 1,
            cost: 5000,
            baseType: "droneRecon",
          },
          {
            id: "2d8e1b7d-04f9-4757-b41a-107fc464cd7f",
            name: "Drill",
            description:
              "Wrenches, spanners, screwdrivers, etc. Can be used as weapons (doing the same Damage as a Crowbar).",
            equipped: true,
            quantity: 0,
            cost: 20,
            baseType: "assortedTools",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "2d661e23-ecbc-4183-95d4-7122eb6dd881",
            name: "Heavy Duty Work Clothes",
            equipped: true,
            armorPoints: 2,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [],
        items: [],
      },
      {
        type: "chaplain",
        id: "52bfa854-305c-434f-9514-a43343f757a9",
        occupation: "Chaplain",
        name: "Olene Rahe",
        pronouns: "She / Her",
        thumbnailPath: "images/characters/PHASE II 23.png",
        salary: 200,
        combat: 10,
        instinct: 20,
        wounds: 0,
        maxWounds: 2,
        loyalty: 21,
        motivation: "",
        equipment: [
          {
            id: "ceca45f4-be67-486e-8151-c344f8c3b5a2",
            name: "Paracord (50m)",
            description: "General purpose lightweight nylon rope.",
            equipped: true,
            quantity: 1,
            cost: 10,
            baseType: "paracord",
          },
        ],
        armor: [
          {
            armorType: "standardBattleDress",
            id: "fa883799-760a-45e4-a243-332608512d39",
            name: "Standard Battle Dress",
            equipped: true,
            armorPoints: 7,
            cost: 750,
            oxygenSupply: 0,
            notes: "Includes short-range comms.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "805f2e5a-6121-46f5-ae66-0331165ea263",
            name: "D&C 7",
            equipped: true,
            cost: 850,
            weaponRange: "close",
            damageString: "1 DMG",
            shots: 3,
            magazineSize: 6,
            critical: "Blunt Force",
            special:
              "If DMG dealt: target must Body Save or be unconscious 1d10 rounds.",
            weaponType: "Tranq Pistol",
            magazines: 0,
            damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
            baseType: "tranqPistol",
          },
        ],
        items: [],
      },
      {
        type: "corporateFixer",
        id: "103b36d2-9303-4e31-a000-c194d4e23aed",
        occupation: "Corporate Fixer",
        name: "Darline Riche",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 75.jpg",
        salary: 5000,
        combat: 15,
        instinct: 30,
        wounds: 0,
        maxWounds: 1,
        loyalty: 23,
        motivation: "",
        equipment: [],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "4b6fe2e4-97f1-4bc2-97dc-746448ead150",
            name: "Standard Crew Attire",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "393845df-1efd-48b7-8ec7-112fd0ff5c13",
            name: "KANO X9",
            equipped: true,
            cost: 1400,
            weaponRange: "close",
            damageString: "1 Wound",
            shots: 4,
            magazineSize: 4,
            critical: "Gunshot",
            special: "1d10 DMG at Long Range.",
            weaponType: "Combat Shotgun",
            magazines: 0,
            damage: [
              { damageType: "fixedWounds", amount: 1, rollMode: null },
              { damageType: "xd10", amount: 1, rollMode: null },
            ],
            baseType: "combatShotgun",
          },
        ],
        items: [
          {
            title: "Cat",
            id: "52b4c525-2eba-49da-b81b-05a7f1d2a30a",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
          {
            title: "Extension Cord (20m)",
            id: "0c515bd9-c170-418e-9a21-61f05b5dc209",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
        ],
      },
      {
        type: "doctor",
        id: "0b79d458-f509-4338-a4d8-aaebb7f57dcc",
        occupation: "Doctor",
        name: "Madge Heitz",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 32.jpg",
        salary: 6000,
        combat: 15,
        instinct: 25,
        wounds: 0,
        maxWounds: 1,
        loyalty: 21,
        motivation: "",
        equipment: [
          {
            id: "de6c9bfd-29a8-4a53-8e62-fe5839b9b0d8",
            name: "Cybernetic Diagnostic Scanner",
            description:
              "Allows the user to scan androids and other cybernetic organisms in order to diagnose any physical or mental issues they may be having. Often distrusted by androids.",
            equipped: true,
            quantity: 1,
            cost: 500,
            baseType: "cyberneticDiagnostic",
          },
          {
            id: "6043fd78-40e5-4136-aaf7-43a98448d1c7",
            name: "Portable Computer Terminal",
            description:
              "Flat computer monitor, keyboard and interface which allows the user to hack into pre-existing computers and networks, as well as perform standard computer tasks.",
            equipped: true,
            quantity: 1,
            cost: 1500,
            baseType: "portableComputerTerminal",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "9cf57cca-71ba-4e36-8a03-8a3100ba3e15",
            name: "Lab Coat",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [],
        items: [],
      },
      {
        type: "engineer",
        id: "e231b165-de04-4399-920e-851447662a8d",
        occupation: "Engineer",
        name: "Essa Cooney",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 12.jpg",
        salary: 4000,
        combat: 20,
        instinct: 25,
        wounds: 0,
        maxWounds: 2,
        loyalty: 24,
        motivation: "",
        equipment: [
          {
            id: "544db096-89b9-45cb-bdac-b8285cf32484",
            name: "Flashlight",
            description:
              "Handheld or shoulder mounted. Illuminates 10m ahead of the user.",
            equipped: true,
            quantity: 1,
            cost: 10,
            baseType: "flashlight",
          },
        ],
        armor: [
          {
            armorType: "vaccsuit",
            id: "39db3eb3-56b1-45de-991f-5b7b8f2cc94a",
            name: "Vaccsuit",
            equipped: true,
            armorPoints: 3,
            cost: 1000,
            oxygenSupply: 12,
            notes:
              "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
            armorSpeed: "disadvantage",
          },
        ],
        weapons: [
          {
            id: "80d4aabc-f2b0-49da-8520-806cb587962c",
            name: "FN Slug",
            equipped: true,
            cost: 750,
            weaponRange: "close",
            damageString: "1d10 DMG [+]",
            shots: 6,
            magazineSize: 6,
            critical: "Gunshot",
            special: "",
            weaponType: "Revolver",
            magazines: 0,
            damage: [{ damageType: "xd10", amount: 1, rollMode: "advantage" }],
            baseType: "revolver",
          },
          {
            id: "ab52ac46-a83b-462a-aab4-f72c27ce3036",
            name: "",
            equipped: true,
            cost: 50,
            weaponRange: "adjacent",
            damageString: "1d5 DMG",
            shots: null,
            magazineSize: null,
            critical: "Blunt Force [+]",
            special: "",
            weaponType: "Crowbar",
            magazines: null,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "crowbar",
          },
        ],
        items: [],
      },
      {
        type: "gunner",
        id: "ab88b534-f2fb-4ab4-a567-633b6a7d20bf",
        occupation: "Gunner",
        name: "Andres Gadd",
        pronouns: "She / Her",
        thumbnailPath: "images/characters/Mothership Chars 34.jpg",
        salary: 1500,
        combat: 30,
        instinct: 25,
        wounds: 0,
        maxWounds: 2,
        loyalty: 24,
        motivation: "",
        equipment: [
          {
            id: "ac3c084f-3b84-4857-b881-6889759e5f86",
            name: "Binoculars",
            description:
              "20x magnification. Add thermal vision (+300cr) or night vision (+1kcr).",
            equipped: true,
            quantity: 1,
            cost: 300,
            baseType: "binoculars",
          },
          {
            id: "b9bb79b6-d136-48b5-90a7-6735f0ecdf88",
            name: "Personal Locator",
            description:
              "Allows crewmembers at a control center (or on the bridge of a ship) to track the location of the wearer.",
            equipped: true,
            quantity: 1,
            cost: 45,
            baseType: "personalLocator",
          },
        ],
        armor: [
          {
            armorType: "standardBattleDress",
            id: "b48ca873-35f4-40e0-860f-845f7b001c87",
            name: "Standard Battle Dress",
            equipped: true,
            armorPoints: 7,
            cost: 750,
            oxygenSupply: 0,
            notes: "Includes short-range comms.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "28d58011-0345-4f84-8423-33b2b4366518",
            name: "SK 109 Seeker",
            equipped: true,
            cost: 12000,
            weaponRange: "long",
            damageString: "1d10x10 DMG",
            shots: 3,
            magazineSize: 3,
            critical: "Gunshot[+]",
            special:
              "If not braced/prone when firing, Body Save or be knocked down.",
            weaponType: "Smart Rifle",
            magazines: 2,
            damage: [{ damageType: "d10x10", amount: 1, rollMode: null }],
            baseType: "smartRifle",
          },
        ],
        items: [],
      },
      {
        type: "marineGrunt",
        id: "a4233b3f-3b0d-412d-aed4-16f98036b55b",
        occupation: "Marine (Grunt)",
        name: "Maryanne Brass",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 38.jpg",
        salary: 1500,
        combat: 30,
        instinct: 25,
        wounds: 0,
        maxWounds: 2,
        loyalty: 24,
        motivation: "",
        equipment: [
          {
            id: "1f808fc5-580d-4a18-90e1-8275cf22a520",
            name: "Stimpak",
            description:
              "Cures cryosickness. Restores 1d10 Health and grants Advantage to Strength and Combat for 2d10 minutes. There is a danger of addiction and/or overdose if used frequently. ",
            equipped: true,
            quantity: 1,
            cost: 600,
            baseType: "stimpak",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "304bac62-9264-4362-9969-7aeaf8bb196f",
            name: "Tank Top and Camo Pants",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "c3d93d01-d3dc-4dc9-8417-0a8a0625ecd6",
            name: "Combat Knife",
            equipped: true,
            cost: 50,
            weaponRange: "adjacent",
            damageString: "1d5 DMG",
            shots: null,
            magazineSize: null,
            critical: "Bleeding [+]",
            special: "",
            weaponType: "Scalpel",
            magazines: null,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "scalpel",
          },
        ],
        items: [],
      },
      {
        type: "marineOfficer",
        id: "b53f0382-755e-41f2-a231-03665581333a",
        occupation: "Marine (Officer)",
        name: "Augustine Lipford",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 59.jpg",
        salary: 2500,
        combat: 35,
        instinct: 35,
        wounds: 0,
        maxWounds: 3,
        loyalty: 27,
        motivation: "",
        equipment: [
          {
            id: "6c48cb84-8d5d-4b7f-87ab-7b79a017f98a",
            name: "Infrared Goggles",
            description:
              "Allows the wearer to see heat signatures, sometimes up to several hours old. Add night vision for (+1kcr).",
            equipped: true,
            quantity: 1,
            cost: 100,
            baseType: "infraredGoggles",
          },
        ],
        armor: [
          {
            armorType: "standardBattleDress",
            id: "a760255c-5a0f-4e9c-96ea-7bbccea6740d",
            name: "Standard Battle Dress",
            equipped: true,
            armorPoints: 7,
            cost: 750,
            oxygenSupply: 0,
            notes: "Includes short-range comms.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "c62cee3b-24e2-4e09-9504-de9cd9656948",
            name: "F20 “Arbiter”",
            equipped: true,
            cost: 2000,
            weaponRange: "long",
            damageString: "3d10 DMG",
            shots: 5,
            magazineSize: 5,
            critical: "Gunshot",
            special: "Pump-action grenade launcher holds x3 frag grenades.",
            weaponType: "Pulse Rifle",
            magazines: 2,
            damage: [{ damageType: "xd10", amount: 3, rollMode: null }],
            baseType: "pulseRifle",
          },
        ],
        items: [],
      },
      {
        type: "pilot",
        id: "e7222825-1c56-49d4-b6c8-c19e0ac99464",
        occupation: "Pilot",
        name: "Rudolph Sweeney",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 59.jpg",
        salary: 3000,
        combat: 15,
        instinct: 25,
        wounds: 0,
        maxWounds: 1,
        loyalty: 25,
        motivation: "",
        equipment: [
          {
            id: "5833bf8f-0588-4593-8f05-35c7c312ed5b",
            name: "Patch Kit",
            description:
              "Repairs punctured and torn vaccsuits, restoring their space readiness. Patched vaccsuits have an AP of 1.",
            equipped: true,
            quantity: 3,
            cost: 200,
            baseType: "patchKit",
          },
          {
            id: "86016036-741e-463b-817d-9b0e91daa02e",
            name: "Assorted Tools",
            description:
              "Wrenches, spanners, screwdrivers, etc. Can be used as weapons (doing the same Damage as a Crowbar).",
            equipped: true,
            quantity: 0,
            cost: 20,
            baseType: "assortedTools",
          },
        ],
        armor: [
          {
            armorType: "vaccsuit",
            id: "9536bfba-88e2-4305-be73-6982b3d99737",
            name: "Vaccsuit",
            equipped: true,
            armorPoints: 3,
            cost: 1000,
            oxygenSupply: 12,
            notes:
              "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
            armorSpeed: "disadvantage",
          },
        ],
        weapons: [
          {
            id: "86a8c3b5-d459-4de8-b863-cb84828d4b03",
            name: "MNC Mode",
            equipped: true,
            cost: 1200,
            weaponRange: "long",
            damageString: "1d100 DMG",
            shots: 6,
            magazineSize: 6,
            critical: "Bleeding [+] or Gore [+]",
            special:
              "Two-handed. Heavy. Must recharge between shots. Reload: 1hr (power), 6hr (solar).",
            weaponType: "Laser Cutter",
            magazines: 1,
            damage: [{ damageType: "d100", amount: 1, rollMode: null }],
            baseType: "laserCutter",
          },
        ],
        items: [],
      },
      {
        type: "pioneer",
        id: "36c44ab5-c720-41ae-b0f3-f847955f70a7",
        occupation: "Pioneer",
        name: "Pearlene Fogarty",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 52.jpg",
        salary: 500,
        combat: 25,
        instinct: 25,
        wounds: 0,
        maxWounds: 1,
        loyalty: 20,
        motivation: "",
        equipment: [
          {
            id: "b7f539b5-8529-4d1c-8209-dc439cc8e342",
            name: "Sample Collection Kit",
            description:
              "Used to research xenoflora and xenofauna in the field. Can take vital signs, DNA samples ,and collect other data on foreign material. Results may not be instaneous and may require a lab for complete analysis.",
            equipped: true,
            quantity: 1,
            cost: 250,
            baseType: "sampleKit",
          },
          {
            id: "6ca3a755-11d4-47cb-b5e3-95e91efe1c91",
            name: "Screwdriver",
            description:
              "Wrenches, spanners, screwdrivers, etc. Can be used as weapons (doing the same Damage as a Crowbar).",
            equipped: true,
            quantity: 0,
            cost: 20,
            baseType: "assortedTools",
          },
        ],
        armor: [
          {
            armorType: "hazardSuit",
            id: "173b208a-a68b-4589-a92f-63b2137a0126",
            name: "Hazard Suit",
            equipped: true,
            armorPoints: 5,
            cost: 750,
            oxygenSupply: 1,
            notes:
              "Includes air filter, extreme heat/cold protection, hydration reclamation (1L of water lasts 4 days), short-range comms, headlamp, and radiation shielding.",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "a40494b3-7908-496a-a54f-e60896fda0ff",
            name: "Halls B Series",
            equipped: true,
            cost: 275,
            weaponRange: "close",
            damageString: "1 DMG",
            shots: 3,
            magazineSize: 3,
            critical: "Blunt Force",
            special:
              "Body Save or become stuck. Strength [-] Check to escape. Quick-hardening foam covers 1sqm.",
            weaponType: "Foam Gun",
            magazines: 1,
            damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
            baseType: "foamGun",
          },
        ],
        items: [],
      },
      {
        type: "scientist",
        id: "9d593d4f-f63a-4d02-a09f-20433b81715a",
        occupation: "Scientist",
        name: "Deedee Bostick",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 17.jpg",
        salary: 1500,
        combat: 15,
        instinct: 10,
        wounds: 0,
        maxWounds: 1,
        loyalty: 20,
        motivation: "",
        equipment: [
          {
            id: "beedc60b-300e-4a98-aa71-d36653e5c000",
            name: "Foldable Stretcher",
            description:
              "Portable stretcher that can fit within a rucksack. Allows the user to safely strap down the patient and carry them to a location where their wounds can be better treated. Unfolds to roughly 2m.",
            equipped: true,
            quantity: 1,
            cost: 100,
            baseType: "foldableStretcher",
          },
          {
            id: "09abd73c-b7f3-4fe5-9ddc-08d2a1bb3822",
            name: "First Aid Kit",
            description:
              "An assortment of bandages and treatments to help stop bleeding, bandage cuts, and treat other minor injuries.",
            equipped: true,
            quantity: 1,
            cost: 75,
            baseType: "firstAidKit",
          },
          {
            id: "c34bb469-5cdb-4c76-96f7-a6f991c5f41f",
            name: "Radiation Pills",
            description:
              "Reduces Radiation Damage (see pg. xx.x) by 2d10 for 2d10 minutes.",
            equipped: true,
            quantity: 5,
            cost: 200,
            baseType: "radiationPills",
          },
        ],
        armor: [
          {
            armorType: "vaccsuit",
            id: "de1f7c36-7c79-48a3-80fe-aa013e48b042",
            name: "Vaccsuit",
            equipped: true,
            armorPoints: 3,
            cost: 1000,
            oxygenSupply: 12,
            notes:
              "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
            armorSpeed: "disadvantage",
          },
        ],
        weapons: [
          {
            id: "962a9753-c040-4cd7-9db9-6c46b0f6ca38",
            name: "Halls B Series",
            equipped: true,
            cost: 275,
            weaponRange: "close",
            damageString: "1 DMG",
            shots: 3,
            magazineSize: 3,
            critical: "Blunt Force",
            special:
              "Body Save or become stuck. Strength [-] Check to escape. Quick-hardening foam covers 1sqm.",
            weaponType: "Foam Gun",
            magazines: 0,
            damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
            baseType: "foamGun",
          },
        ],
        items: [],
      },
      {
        type: "survivalGuide",
        id: "56b2b7c6-0b80-48bb-8db9-1c26254bae77",
        occupation: "Survival Guide",
        name: "Thalia Gillingham",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 44.jpg",
        salary: 2000,
        combat: 30,
        instinct: 35,
        wounds: 0,
        maxWounds: 2,
        loyalty: 27,
        motivation: "In huge debt to a powerful crime syndicate.",
        equipment: [
          {
            id: "901862e9-c8eb-4514-b83f-b268ddcaca66",
            name: "Cybernetic Diagnostic Scanner",
            description:
              "Allows the user to scan androids and other cybernetic organisms in order to diagnose any physical or mental issues they may be having. Often distrusted by androids.",
            equipped: true,
            quantity: 1,
            cost: 500,
            baseType: "cyberneticDiagnostic",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "3912ebcd-144c-4df1-a2f9-a8a37fed34ca",
            name: "Standard Crew Attire",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "4bff3e93-92b7-42a8-8bb1-c412660be934",
            name: "Utility Knife",
            equipped: true,
            cost: 50,
            weaponRange: "adjacent",
            damageString: "1d5 DMG",
            shots: null,
            magazineSize: null,
            critical: "Bleeding [+]",
            special: "",
            weaponType: "Scalpel",
            magazines: null,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "scalpel",
          },
        ],
        items: [
          {
            title: "Duct Tape",
            id: "a1fddecb-c501-4cd4-8605-897d7b8434a5",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
        ],
      },
      {
        type: "surgeon",
        id: "de46f3e7-58cb-4de6-9e0d-3e383e901fd4",
        occupation: "Surgeon",
        name: "Chrissy Saucedo",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 04.jpg",
        salary: 7000,
        combat: 15,
        instinct: 20,
        wounds: 0,
        maxWounds: 1,
        loyalty: 25,
        motivation: "",
        equipment: [
          {
            id: "116555cc-077b-4ffb-9f21-9151cb9a6bf3",
            name: "Sample Collection Kit",
            description:
              "Used to research xenoflora and xenofauna in the field. Can take vital signs, DNA samples ,and collect other data on foreign material. Results may not be instaneous and may require a lab for complete analysis.",
            equipped: true,
            quantity: 1,
            cost: 250,
            baseType: "sampleKit",
          },
          {
            id: "4bae663a-2319-4e68-949d-4907defb97b9",
            name: "Flashlight",
            description:
              "Handheld or shoulder mounted. Illuminates 10m ahead of the user.",
            equipped: true,
            quantity: 1,
            cost: 10,
            baseType: "flashlight",
          },
        ],
        armor: [
          {
            armorType: "vaccsuit",
            id: "2242eefb-b5df-4974-a6e6-2c1ef0fd6df0",
            name: "Vaccsuit",
            equipped: true,
            armorPoints: 3,
            cost: 1000,
            oxygenSupply: 12,
            notes:
              "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
            armorSpeed: "disadvantage",
          },
        ],
        weapons: [
          {
            id: "8ff97137-970d-4d03-b5a8-ad7060985ed6",
            name: "HAN-290",
            equipped: true,
            cost: 350,
            weaponRange: "close",
            damageString: "1d10 DMG + 2d10 DMG when removed.",
            shots: 1,
            magazineSize: 1,
            critical: "Bleeding [+]",
            special: "100m micro-filament. Body Save or become entangled.",
            weaponType: "Rigging Gun",
            magazines: 0,
            damage: [
              { damageType: "xd10", amount: 1, rollMode: null },
              { damageType: "xd10", amount: 2, rollMode: null },
            ],
            baseType: "riggingGun",
          },
        ],
        items: [
          {
            title: "Lab Rat",
            id: "0e26a287-b7e0-485e-9e33-5b0d050240fd",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
        ],
      },
      {
        type: "teamster",
        id: "4dae77fc-2193-4606-a355-93459dd4950e",
        occupation: "Teamster",
        name: "Emelia Lucky",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 06.jpg",
        salary: 1500,
        combat: 25,
        instinct: 25,
        wounds: 0,
        maxWounds: 1,
        loyalty: 23,
        motivation: "",
        equipment: [],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "65656308-1f84-42aa-8e78-3cd83681c1f7",
            name: "Standard Crew Attire",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "785798dc-e440-4cf2-bd91-b70f5152bb84",
            name: "Rosco SS6",
            equipped: true,
            cost: 150,
            weaponRange: "close",
            damageString: "1d5 DMG",
            shots: 32,
            magazineSize: 32,
            critical: "Bleeding",
            special: "",
            weaponType: "Nailgun",
            magazines: 0,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "nailGun",
          },
        ],
        items: [
          {
            title: "Head Lamp",
            id: "a8c31ea2-1d3b-4473-9530-7c7cc66923aa",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
          {
            title: "Satchel",
            id: "57c74652-5f0c-4122-9462-f3d920a3aca3",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
          {
            title: "Lunch Box",
            id: "c69c814c-0535-4f52-8aae-d29e74b18429",
            subtitle: null,
            description: null,
            cost: 0,
            quantity: 1,
          },
        ],
      },
      {
        type: "therapist",
        id: "40e68305-8732-4b14-8b4f-e025d19018ba",
        occupation: "Therapist",
        name: "Mohamed Knoblauch",
        pronouns: "He / Him",
        thumbnailPath: "images/characters/Mothership Chars 34.jpg",
        salary: 1000,
        combat: 10,
        instinct: 20,
        wounds: 0,
        maxWounds: 1,
        loyalty: 14,
        motivation: "",
        equipment: [
          {
            id: "acbb0af8-ab9c-41a5-8e6b-40889e8f78d2",
            name: "Foldable Stretcher",
            description:
              "Portable stretcher that can fit within a rucksack. Allows the user to safely strap down the patient and carry them to a location where their wounds can be better treated. Unfolds to roughly 2m.",
            equipped: true,
            quantity: 1,
            cost: 100,
            baseType: "foldableStretcher",
          },
          {
            id: "ebd2f9cd-2789-43a9-9e02-28128996a154",
            name: "First Aid Kit",
            description:
              "An assortment of bandages and treatments to help stop bleeding, bandage cuts, and treat other minor injuries.",
            equipped: true,
            quantity: 1,
            cost: 75,
            baseType: "firstAidKit",
          },
          {
            id: "448f0555-657c-4fff-85b7-1dee51f65962",
            name: "Radiation Pills",
            description:
              "Reduces Radiation Damage (see pg. xx.x) by 2d10 for 2d10 minutes.",
            equipped: true,
            quantity: 5,
            cost: 200,
            baseType: "radiationPills",
          },
        ],
        armor: [
          {
            armorType: "vaccsuit",
            id: "3c28cc9a-a1e0-4193-a831-caf740abf1b1",
            name: "Vaccsuit",
            equipped: true,
            armorPoints: 3,
            cost: 1000,
            oxygenSupply: 12,
            notes:
              "Includes short-range comms, headlamp, and radiation shielding. Decompression within 1d5 rounds if punctured.",
            armorSpeed: "disadvantage",
          },
        ],
        weapons: [
          {
            id: "984afbbb-25d0-4cdb-b286-bda05332cbd1",
            name: "Halls B Series",
            equipped: true,
            cost: 275,
            weaponRange: "close",
            damageString: "1 DMG",
            shots: 3,
            magazineSize: 3,
            critical: "Blunt Force",
            special:
              "Body Save or become stuck. Strength [-] Check to escape. Quick-hardening foam covers 1sqm.",
            weaponType: "Foam Gun",
            magazines: 0,
            damage: [{ damageType: "fixedDamage", amount: 1, rollMode: null }],
            baseType: "foamGun",
          },
        ],
        items: [],
      },
      {
        type: "voidUrchin",
        id: "7ed60887-5a7b-4046-b813-f3eca69a6dfa",
        occupation: "Void Urchin",
        name: "Kael Gorsuch",
        pronouns: "They / Them",
        thumbnailPath: "images/characters/Mothership Chars 59.jpg",
        salary: 100,
        combat: 30,
        instinct: 40,
        wounds: 0,
        maxWounds: 2,
        loyalty: 20,
        motivation: "",
        equipment: [
          {
            id: "2c19a38f-d317-4c8a-97bc-f7bf05f99efa",
            name: "Bioscanner",
            description:
              "Allows the user to scan the immediate area for signs of life. Generally can scan for 100m in all directions, without being blocked by most known metals. Can tell the location of signs of life, but not what that life is.",
            equipped: true,
            quantity: 1,
            cost: 150,
            baseType: "bioscanner",
          },
        ],
        armor: [
          {
            armorType: "standardCrewAttire",
            id: "69ed54fc-c231-490c-a7b6-1c250bb23a73",
            name: "Standard Crew Attire",
            equipped: true,
            armorPoints: 1,
            cost: 20,
            oxygenSupply: 0,
            notes: "",
            armorSpeed: "normal",
          },
        ],
        weapons: [
          {
            id: "1b524917-7f3a-4e87-bdeb-ce9368761a83",
            name: "",
            equipped: true,
            cost: 50,
            weaponRange: "adjacent",
            damageString: "1d5 DMG",
            shots: null,
            magazineSize: null,
            critical: "Bleeding [+]",
            special: "",
            weaponType: "Scalpel",
            magazines: null,
            damage: [{ damageType: "xd5", amount: 1, rollMode: null }],
            baseType: "scalpel",
          },
        ],
        items: [],
      },
    ],
  };
  